baseURL = 'https://gyu85.github.io/'
locale = 'ko-kr'
title = 'MyNoteBooks'
theme = 'gyu-hugo-PaperMod'
hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

[params]
    env = "production"
    title = "내 개발 & 일상 노트"
    description = "조용히 기록하는 개인 공간"
    defaultTheme = "auto"

[[menu.main]]
    name = "개발 기록"
    url = "/devs/"
    weight = 10

